# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
