# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

parameters:
    commonmark.configuration:
        allow_unsafe_links: false
        html_input: escape
        max_nesting_level: 25
        renderer:
            soft_break: "<br/>\r\n"
        table:
            wrap:
                enabled: true
                tag: "div"
                attributes:
                    class: "user-content-table-responsive"
    commonmark.allowed_schemes: [http, https]

services:
    _defaults:
        autowire: true
        public: false

    League\CommonMark\Extension\Autolink\UrlAutolinkParser:
        arguments:
            $allowedProtocols: "%commonmark.allowed_schemes%"
    League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension: ~
    League\CommonMark\Extension\Strikethrough\StrikethroughExtension: ~
    League\CommonMark\Extension\Table\TableExtension: ~
