fos_elastica:
  clients:
    default: { url: '%env(ELASTICSEARCH_URL)%' }
  indexes:
    magazines:
      properties:
        id: ~
        name: { "type": "keyword" }
        title: { boost: 20, analyzer: morfologik }
        description: { analyzer: morfologik }
        rules: { analyzer: morfologik }
        createdAt: { "type": "date" }
        visibility: ~
        cover:
          type: "object"
          properties:
            id: ~
            filePath: ~
        tags:
          property_path: false
        body:
          property_path: false
      persistence:
        driver: orm
        model: App\Entity\Magazine
        listener: '%elastica_listener%'
    entries:
      properties:
        id: ~
        title: { boost: 10, analyzer: morfologik }
        url: ~
        body: { boost: 10, analyzer: morfologik }
        type: ~
        ranking: ~
        score: ~
        isAdult: ~
        sticky: ~
        createdAt: { "type": "date" }
        lastActive: ~
        visibility: ~
        magazine:
          type: "object"
          properties:
            name: ~
        domain:
          type: "object"
          properties:
            id: ~
            name: ~
        user:
          type: "object"
          properties:
            username: { "type": "keyword" }
        image:
          type: "object"
          properties:
            id: ~
            filePath: ~
        tags:
          property_path: false
      persistence:
        driver: orm
        model: App\Entity\Entry
        listener: '%elastica_listener%'
    entry_comments:
      properties:
        id: ~
        body: { analyzer: morfologik }
        createdAt: { "type": "date" }
        lastActive: ~
        visibility: ~
        magazine:
          type: "object"
          properties:
            name: { "type": "keyword" }
        entry:
          type: "object"
          properties:
            id: ~
        user:
          type: "object"
          properties:
            username: { "type": "keyword" }
        image:
          type: "object"
          properties:
            id: ~
            filePath: ~
        tags:
          property_path: false
      persistence:
        driver: orm
        model: App\Entity\EntryComment
        listener: '%elastica_listener%'
    posts:
      properties:
        id: ~
        body: { analyzer: morfologik }
        ranking: ~
        score: ~
        isAdult: ~
        createdAt: { "type": "date" }
        lastActive: ~
        visibility: ~
        magazine:
          type: "object"
          properties:
            name: { "type": "keyword" }
        user:
          type: "object"
          properties:
            username: { "type": "keyword" }
        image:
          type: "object"
          properties:
            id: ~
            filePath: ~
        tags:
          property_path: false
      persistence:
        driver: orm
        model: App\Entity\Post
        listener: '%elastica_listener%'
    post_comments:
      properties:
        id: ~
        body: { analyzer: morfologik }
        createdAt: { "type": "date" }
        lastActive: ~
        visibility: ~
        magazine:
          type: "object"
          properties:
            name: { "type": "keyword" }
        post:
          type: "object"
          properties:
            id: ~
        user:
          type: "object"
          properties:
            username: { "type": "keyword" }
        image:
          type: "object"
          properties:
            id: ~
            filePath: ~
        tags:
          property_path: false
      persistence:
        driver: orm
        model: App\Entity\PostComment
        listener: '%elastica_listener%'
