# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

fos_js_routing:
  routes_to_expose: [
    'ajax_fetch_entry',
    'ajax_fetch_entry_comment',
    'ajax_fetch_post',
    'ajax_fetch_post_comment',
    'ajax_fetch_post_comments',
    'ajax_fetch_user_popup',
    'ajax_fetch_title',
    'ajax_fetch_embed',
    'ajax_fetch_duplicates'
  ]
