# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
#  cache: cached_s3_client
  driver: "gd"
  webp:
    generate: true

  filter_sets:
    entry_thumb:
      quality: 90
      filters:
        thumbnail: { size: [ 380, 380 ], mode: inset }
    avatar_thumb:
      quality: 90
      filters:
        thumbnail: { size: [ 100, 100 ], mode: fixed }
    post_thumb:
      quality: 90
      filters:
        thumbnail: { size: [ 600, 500 ], mode: inset }
    user_cover:
      quality: 90
      filters:
        thumbnail: { size: [ 1500, 500 ], mode: fixed }

  loaders:
    local_images:
      flysystem:
        filesystem_service: League\Flysystem\Filesystem

  data_loader: local_images

  resolvers:
    entry_thumb:
      flysystem:
        filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
        root_url:           '%uploads_base_url%'
        cache_prefix:       media/cache
        visibility:         public

    avatar_thumb:
      flysystem:
        filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
        root_url: '%uploads_base_url%'
        cache_prefix: media/cache
        visibility: public

    post_thumb:
      flysystem:
        filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
        root_url: '%uploads_base_url%'
        cache_prefix: media/cache
        visibility: public

    user_cover:
      flysystem:
        filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
        root_url: '%uploads_base_url%'
        cache_prefix: media/cache
        visibility: public
