# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
