# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

debril_rss_atom:
    # switch to true if you need to set cache-control: private
    private: false
    # switch to true if you need to always send status 200
    force_refresh: true
    content_type_xml: application/rss+xml
