# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

framework:
  default_locale: '%env(KBIN_DEFAULT_LANG)%'
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks: ['en']
