twig:
    globals:
        kbin_domain: '%env(KBIN_DOMAIN)%'
        kbin_js_enabled: '%env(bool:KBIN_JS_ENABLED)%'

    default_path: '%kernel.project_dir%/templates'
    form_themes: ['_layout/bootstrap_4_layout.html.twig']
