# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

_errors:
  resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
  prefix: /_error
