# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

oauth2_server:
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
    type: php
