# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

ux_autocomplete:
    resource: '@AutocompleteBundle/config/routes.php'
    prefix: '/autocomplete'
