# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

App\DTO\DomainDto:
  attributes:
    name:
      groups: [ 'domain:collection:get', 'domain:item:get', 'entry:collection:get', 'entry:item:get' ]
    entryCount:
      groups: [ 'domain:collection:get', 'domain:item:get', 'entry:item:get' ]
