App\DTO\EntryDto:
  attributes:
    id:
      groups: [ 'entry_read' ]
    magazine:
      groups: [ 'entry_read' ]
    user:
      groups: [ 'entry_read' ]
    image:
      groups: [ 'entry_read' ]
    title:
      groups: [ 'entry_read' ]
    url:
      groups: [ 'entry_read' ]
    body:
      groups: [ 'entry_read' ]
    type:
      groups: [ 'entry_read' ]
    comments:
      groups: [ 'entry_read' ]
    uv:
      groups: [ 'entry_read' ]
    dv:
      groups: [ 'entry_read' ]
    views:
      groups: [ 'entry_read' ]
