App\DTO\EntryCommentDto:
  attributes:
    id:
      groups: [ 'entry:comment:collection:get', 'entry:comment:item:get' ]
    magazine:
      groups: [ 'entry:comment:item:get' ]
    user:
      groups: [ 'entry:comment:collection:get', 'entry:comment:item:get' ]
    entry:
      groups: [ 'entry:comment:item:get' ]
    image:
      groups: [ 'entry:comment:collection:get', 'entry:comment:item:get' ]
    parent:
      groups: [ 'entry:comment:collection:get', 'entry:comment:item:get' ]
    root:
      groups: [ 'entry:comment:collection:get', 'entry:comment:item:get' ]
    body:
      groups: [ 'entry:comment:collection:get', 'entry:comment:item:get' ]
    uv:
      groups: [ 'entry:comment:collection:get', 'entry:comment:item:get' ]
    dv:
      groups: [ 'entry:comment:collection:get', 'entry:comment:item:get' ]
    createdAt:
      groups: [ 'entry:comment:collection:get', 'entry:comment:item:get' ]
    lastActive:
      groups: [ 'entry:comment:collection:get', 'entry:comment:item:get' ]

