# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

App\DTO\ImageDto:
  attributes:
    id:
      groups: [ 'image:get' ]
    filePath:
      groups: [ 'image:get','magazine:collection:get', 'magazine:item:get', 'entry:collection:get', 'entry:item:get', 'entry:comment:collection:get', 'single:entry:comment:collection:get', 'post:collection:get', 'post:item:get', 'post:comment:collection:get', 'single:post:comment:collection:get' ]
    width:
      groups: [ 'image:get','magazine:collection:get', 'magazine:item:get','entry:collection:get', 'entry:item:get', 'entry:comment:collection:get', 'single:entry:comment:collection:get', 'post:collection:get', 'post:item:get', 'post:comment:collection:get', 'single:post:comment:collection:get' ]
    height:
      groups: [ 'image:get','magazine:collection:get', 'magazine:item:get','entry:collection:get', 'entry:item:get', 'entry:comment:collection:get', 'single:entry:comment:collection:get', 'post:collection:get', 'post:item:get', 'post:comment:collection:get', 'single:post:comment:collection:get' ]
