App\DTO\ImageDto:
  attributes:
    id:
      groups: [ 'image:get' ]
    filePath:
      groups: [ 'image:get', 'entry:collection:get', 'entry:item:get', 'entry:comment:collection:get' ]
    width:
      groups: [ 'image:get', 'entry:collection:get', 'entry:item:get', 'entry:comment:collection:get' ]
    height:
      groups: [ 'image:get', 'entry:collection:get', 'entry:item:get', 'entry:comment:collection:get' ]
