App\DTO\ImageDto:
  attributes:
    id:
      groups: [ 'image_read' ]
    filePath:
      groups: [ 'image_read', 'entry_read' ]
    width:
      groups: [ 'image_read', 'entry_read' ]
    height:
      groups: [ 'image_read', 'entry_read' ]
