App\DTO\MagazineDto:
  attributes:
    name:
      groups: [ 'magazine_read' ]
    title:
      groups: [ 'magazine_read' ]
    description:
      groups: [ 'magazine_read' ]
    rules:
      groups: [ 'magazine_read' ]
