App\DTO\MagazineDto:
  attributes:
    name:
      groups: [ 'magazine_read', 'magazine_write', 'entry:collection:get', 'entry:item:get', 'entry:comment:collection:get', 'single:entry:comment:collection:get', 'post:collection:get', 'post:item:get', 'post:comment:collection:get', 'single:post:comment:collection:get' ]
    title:
      groups: [ 'magazine_read', 'magazine_write' ]
    description:
      groups: [ 'magazine_read', 'magazine_write' ]
    rules:
      groups: [ 'magazine_read', 'magazine_write' ]
