App\DTO\MagazineDto:
  attributes:
    name:
      groups: [ 'magazine_read', 'magazine_write', 'entry:collection:get', 'entry:item:get' ]
    title:
      groups: [ 'magazine_read', 'magazine_write' ]
    description:
      groups: [ 'magazine_read', 'magazine_write' ]
    rules:
      groups: [ 'magazine_read', 'magazine_write' ]
