App\DTO\PostDto:
  attributes:
    id:
      groups: [ 'post_read' ]
    user:
      groups: [ 'entry_read' ]
    magazine:
      groups: [ 'entry_read' ]
    image:
      groups: [ 'entry_read' ]
    body:
      groups: [ 'post_read' ]
