App\DTO\UserDto:
  attributes:
    email:
      groups: [ 'user:write' ]
    plainPassword:
      groups: [ 'user:write' ]
    username:
      groups: [ 'user:read', 'user_write', 'entry:collection:get', 'entry:item:get', 'entry:comment:collection:get' ]
    avatar:
      groups: [ 'user:read', 'entry:item:get', 'entry:comment:collection:get' ]
