App\DTO\UserDto:
  attributes:
    email:
      groups: [ 'user:write' ]
    plainPassword:
      groups: [ 'user:write' ]
    username:
      groups: [ 'user:get', 'entry:collection:get', 'entry:item:get', 'entry:comment:collection:get', 'single:entry:comment:collection:get', 'post:item:get', 'post:collection:get', 'post:comment:collection:get', 'single:post:comment:collection:get' ]
    avatar:
      groups: [ 'user:get', 'entry:item:get', 'entry:comment:collection:get', 'single:entry:comment:collection:get', 'post:item:get', 'post:collection:get', 'single:post:comment:collection:get' ]
