# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

App\DTO\UserDto:
  attributes:
    email:
      groups: [ 'user:write' ]
    plainPassword:
      groups: [ 'user:write' ]
    username:
      groups: [ 'user:get', 'magazine:item:get', 'magazine:collection:get', 'entry:collection:get', 'entry:item:get', 'entry:comment:collection:get', 'single:entry:comment:collection:get', 'post:item:get', 'post:collection:get', 'post:comment:collection:get', 'single:post:comment:collection:get' ]
    avatar:
      groups: [ 'user:get', 'magazine:item:get', 'entry:item:get', 'entry:comment:collection:get', 'single:entry:comment:collection:get', 'post:item:get', 'post:collection:get', 'single:post:comment:collection:get' ]
