# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

app.swagger_ui:
  path: /api/docs
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
