cardano_wallet_new:
  controller: App\Controller\Cardano\CardanoCreateWalletController
  path: /cardano/wallet
  methods: [ GET, POST ]

cardano_transaction:
  controller: App\Controller\Cardano\CardanoTransactionController
  path: /cardano/transaction
  methods: [ POST ]
