entry_create:
  controller: App\Controller\EntryController::create
  defaults: { type: null }
  path: /nowaTresc/{type}
  methods: [ GET, POST ]

magazine_entry_create:
  controller: App\Controller\EntryController::create
  defaults: { type: null }
  path: /m/{name}/nowaTresc/{type}
  methods: [ GET, POST ]

entry_edit:
  controller: App\Controller\EntryController::edit
  path: /m/{magazine_name}/t/{entry_id}/edytuj
  methods: [ GET, POST ]

entry_delete:
  controller: App\Controller\EntryController::delete
  path: /m/{magazine_name}/t/{entry_id}/delete
  methods: [ POST ]

entry_purge:
  controller: App\Controller\EntryController::purge
  path: /m/{magazine_name}/t/{entry_id}/purge
  methods: [ POST ]

entry_pin:
  controller: App\Controller\EntryPinController
  path: /m/{magazine_name}/t/{entry_id}/pin
  methods: [ POST ]

entry_single:
  controller: App\Controller\EntryController::single
  defaults: { sortBy: ~ }
  path: /m/{magazine_name}/t/{entry_id}/{sortBy}
  methods: [ GET ]

entry_vote:
  controller: App\Controller\VoteController
  defaults: { entityClass: App\Entity\Entry }
  path: /ev/{id}/{choice}
  methods: [POST]

entry_report:
  controller: App\Controller\ReportController
  defaults: { entityClass: App\Entity\Entry }
  path: /er/{id}
  methods: [ GET, POST ]
