entry_create:
  controller: App\Controller\Entry\EntryCreateController
  defaults: { type: null }
  path:
    en: /new/{type}
    pl: /nowy/{type}
  methods: [ GET, POST ]

magazine_entry_create:
  controller: App\Controller\Entry\EntryCreateController
  defaults: { type: null }
  path:
    en: /m/{name}/new/{type}
    pl: /m/{name}/nowy/{type}
  methods: [ GET, POST ]

entry_edit:
  controller: App\Controller\Entry\EntryEditController
  defaults: { slug: -, sortBy: ~ }
  path:
    en: /m/{magazine_name}/t/{entry_id}/{slug}/edit
    pl: /m/{magazine_name}/t/{entry_id}/{slug}/edytuj
  methods: [ GET, POST ]

entry_delete:
  controller: App\Controller\Entry\EntryDeleteController::delete
  defaults: { slug: -, sortBy: ~ }
  path: /m/{magazine_name}/t/{entry_id}/{slug}/delete
  methods: [ POST ]

entry_purge:
  controller: App\Controller\Entry\EntryDeleteController::purge
  defaults: { slug: -, sortBy: ~ }
  path: /m/{magazine_name}/t/{entry_id}/{slug}/purge
  methods: [ POST ]

entry_pin:
  controller: App\Controller\Entry\EntryPinController
  defaults: { slug: -, sortBy: ~ }
  path: /m/{magazine_name}/t/{entry_id}/{slug}/pin
  methods: [ POST ]

entry_voters:
  controller: App\Controller\Entry\EntryVotersController
  defaults: { slug: -, sortBy: ~ }
  path:
    en: /m/{magazine_name}/t/{entry_id}/{slug}/votes
    pl: /m/{magazine_name}/t/{entry_id}/{slug}/głosy
  methods: [ GET ]

entry_single:
  controller: App\Controller\Entry\EntrySingleController
  defaults: { slug: -, sortBy: ~ }
  path: /m/{magazine_name}/t/{entry_id}/{slug}/{sortBy}
  methods: [ GET ]

entry_single_comments:
  controller: App\Controller\Entry\EntrySingleController
  defaults: { slug: -, sortBy: ~ }
  path:
    en: /m/{magazine_name}/t/{entry_id}/{slug}/comments/{sortBy}
    pl: /m/{magazine_name}/t/{entry_id}/{slug}/komentarze/{sortBy}
  methods: [ GET ]

entry_vote:
  controller: App\Controller\VoteController
  defaults: { entityClass: App\Entity\Entry }
  path: /ev/{id}/{choice}
  methods: [POST]

entry_report:
  controller: App\Controller\ReportController
  defaults: { entityClass: App\Entity\Entry }
  path: /er/{id}
  methods: [ GET, POST ]
