entry_create:
  controller: App\Controller\Entry\EntryController::create
  defaults: { type: null }
  path: /nowaTresc/{type}
  methods: [ GET, POST ]

magazine_entry_create:
  controller: App\Controller\Entry\EntryController::create
  defaults: { type: null }
  path: /m/{name}/nowaTresc/{type}
  methods: [ GET, POST ]

entry_edit:
  controller: App\Controller\Entry\EntryController::edit
  defaults: { slug: -, sortBy: ~ }
  path: /m/{magazine_name}/t/{entry_id}/{slug}/edytuj
  methods: [ GET, POST ]

entry_delete:
  controller: App\Controller\Entry\EntryController::delete
  defaults: { slug: -, sortBy: ~ }
  path: /m/{magazine_name}/t/{entry_id}/{slug}/delete
  methods: [ POST ]

entry_purge:
  controller: App\Controller\Entry\EntryController::purge
  defaults: { slug: -, sortBy: ~ }
  path: /m/{magazine_name}/t/{entry_id}/{slug}/purge
  methods: [ POST ]

entry_pin:
  controller: App\Controller\Entry\EntryPinController
  defaults: { slug: -, sortBy: ~ }
  path: /m/{magazine_name}/t/{entry_id}/{slug}/pin
  methods: [ POST ]

entry_single:
  controller: App\Controller\Entry\EntryController::single
  defaults: { slug: -, sortBy: ~ }
  path: /m/{magazine_name}/t/{entry_id}/{slug}/komentarze/{sortBy}
  methods: [ GET ]

entry_vote:
  controller: App\Controller\VoteController
  defaults: { entityClass: App\Entity\Entry }
  path: /ev/{id}/{choice}
  methods: [POST]

entry_report:
  controller: App\Controller\ReportController
  defaults: { entityClass: App\Entity\Entry }
  path: /er/{id}
  methods: [ GET, POST ]
