magazine_panel_front:
  controller: App\Controller\Magazine\MagazinePanelController::front
  path: /m/{name}/panel/statystyki
  methods: [ GET ]

magazine_panel_bans:
  controller: App\Controller\Magazine\MagazinePanelBanController::bans
  path: /m/{name}/panel/bany
  methods: [ GET, POST ]

magazine_panel_ban:
  controller: App\Controller\Magazine\MagazinePanelBanController::ban
  path: /m/{magazine_name}/ban/{user_username}
  methods: [ GET, POST ]

magazine_panel_unban:
  controller: App\Controller\Magazine\MagazinePanelBanController::unban
  path: /m/{magazine_name}/unban/{user_username}
  methods: [ POST ]

magazine_panel_edit:
  controller: App\Controller\Magazine\MagazinePanelController::edit
  path: /m/{name}/panel/edytuj
  methods: [ GET, POST ]

magazine_panel_moderators:
  controller: App\Controller\Magazine\MagazinePanelModController::moderators
  path: /m/{name}/panel/moderatorzy
  methods: [ GET, POST ]

magazine_panel_moderator_purge:
  controller: App\Controller\Magazine\MagazinePanelModController::deleteModerator
  path: /m/{magazine_name}/panel/{moderator_id}/purge
  methods: [ POST ]

magazine_panel_reports:
  controller: App\Controller\Magazine\MagazinePanelReportController::reports
  path: /m/{name}/panel/zgloszenia
  methods: [ GET ]

magazine_panel_report_approve:
  controller: App\Controller\Magazine\MagazinePanelReportController::reportApprove
  path: /m/{magazine_name}/panel/zgloszenia/{report_id}/approve
  methods: [ POST ]

magazine_panel_report_reject:
  controller: App\Controller\Magazine\MagazinePanelReportController::reportReject
  path: /m/{magazine_name}/panel/zgloszenia/{report_id}/reject
  methods: [ POST ]

magazine_panel_theme:
  controller: App\Controller\Magazine\MagazinePanelController::theme
  path: /m/{name}/panel/wyglad
  methods: [ GET, POST ]

magazine_panel_badges:
  controller: App\Controller\Magazine\MagazinePanelBadgeController::badges
  path: /m/{name}/panel/etykiety
  methods: [ GET, POST ]

magazine_panel_badge_remove:
  controller: App\Controller\MagazinePanelBadgeController::removeBadge
  path: /m/{magazine_name}/panel/etykiety/{badge_id}/purge
  methods: [ POST ]
