user_profile_messages:
  controller: App\Controller\MessageController::threads
  path:
    en: /profile/messages
    pl: /profil/wiadomości
  methods: [ GET ]

user_profile_message:
  controller: App\Controller\MessageController::thread
  path:
    en: /profile/messages/{id}
    pl: /profil/wiadomości/{id}
  methods: [ GET, POST ]

user_message:
  controller: App\Controller\MessageController::createThread
  path:
    en: /u/{username}/message
    pl: /u/{username}/wiadomość
  methods: [ GET, POST ]
