# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

messages_front:
  controller: App\Controller\Message\MessageThreadListController
  path: /profile/messages
  methods: [ GET ]

messages_single:
  controller: App\Controller\Message\MessageThreadController
  path: /profile/messages/{id}
  methods: [ GET, POST ]

messages_create:
  controller: App\Controller\Message\MessageCreateThreadController
  path: /u/{username}/message
  methods: [ GET, POST ]
