# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

people_front:
  controller: App\Controller\People\PeopleFrontController
  path: /people
  methods: [ GET ]
