post_comment_create:
  controller: App\Controller\Post\Comment\CommentCreateController
  defaults: { slug: -, parent_comment_id: null }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/reply/{parent_comment_id}
    pl: /m/{magazine_name}/w/{post_id}/{slug}/odpowiedź/{parent_comment_id}
  methods: [ GET, POST ]

post_comment_edit:
  controller: App\Controller\Post\Comment\CommentEditController
  defaults: { slug: -, }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/reply/{comment_id}/edit
    pl: /m/{magazine_name}/w/{post_id}/{slug}/odpowiedź/{comment_id}/edytuj
  methods: [ GET, POST ]

post_comment_delete:
  controller: App\Controller\Post\Comment\CommentDeleteController::delete
  defaults: { slug: -, }
  path: /m/{magazine_name}/p/{post_id}/{slug}/reply/{comment_id}/delete
  methods: [ POST ]

post_comment_purge:
  controller: App\Controller\Comment\CommentDeleteController::purge
  defaults: { slug: -, }
  path: /m/{magazine_name}/p/{post_id}/{slug}/reply/{comment_id}/purge
  methods: [ POST ]

post_comment_vote:
  controller: App\Controller\VoteController
  defaults: { entityClass: App\Entity\PostComment }
  path: /pcv/{id}/{choice}
  methods: [POST]

post_comment_report:
  controller: App\Controller\ReportController
  defaults: { entityClass: App\Entity\PostComment }
  path: /pcr/{id}
  methods: [ GET, POST ]
