post_comment_create:
  controller: App\Controller\Post\PostCommentController::create
  defaults: { parent_comment_id: null }
  path: /m/{magazine_name}/w/{post_id}/komentarz/{parent_comment_id}
  methods: [ GET, POST ]

post_comment_edit:
  controller: App\Controller\Post\PostCommentController::edit
  path: /m/{magazine_name}/w/{post_id}/komentarz/{comment_id}/edytuj
  methods: [ GET, POST ]

post_comment_delete:
  controller: App\Controller\Post\PostCommentController::delete
  path: /m/{magazine_name}/w/{post_id}/komentarz/{comment_id}/delete
  methods: [ POST ]

post_comment_purge:
  controller: App\Controller\Post\PostCommentController::purge
  path: /m/{magazine_name}/w/{post_id}/komentarz/{comment_id}/purge
  methods: [ POST ]

post_comment_vote:
  controller: App\Controller\VoteController
  defaults: { entityClass: App\Entity\PostComment }
  path: /pcv/{id}/{choice}
  methods: [POST]

post_comment_report:
  controller: App\Controller\ReportController
  defaults: { entityClass: App\Entity\PostComment }
  path: /pcr/{id}
  methods: [ GET, POST ]
