# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

api_search:
  controller: App\Controller\Api\Search\SearchRetrieveApi
  path: /api/search
  methods: [ GET ]
  format: json
