# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

search:
  controller: App\Controller\SearchController
  path: /search/{sortBy}/{time}/{type}
  defaults: { sortBy: newest, time: '∞', type: ~ }
  methods: [GET]
