app_register:
  controller: App\Controller\Security\RegisterController
  path:
    en: /register
    pl: /zarejestruj
  methods: [ GET, POST ]

app_verify_email:
  controller: App\Controller\Security\VerifyEmailController
  path:
    en: /verify/email
    pl: /zweryfikuj/email
  methods: [ GET ]

app_forgot_password_request:
  controller: App\Controller\Security\ResetPasswordController::request
  path:
    en: /reset-password
    pl: /resetuj-hasło
  methods: [ GET, POST ]

app_check_email:
  controller: App\Controller\Security\ResetPasswordController::checkEmail
  path: /reset-password/check-email
  methods: [ GET, POST ]

app_reset_password:
  controller: App\Controller\Security\ResetPasswordController::reset
  defaults: { token: ~ }
  path:
    en: /reset-password/reset/{token}
    pl: /resetuj-hasło/reset/{token}
  methods: [ GET, POST ]

app_login:
  controller: App\Controller\Security\LoginController
  path:
    en: /login
    pl: /zaloguj
  methods: [ GET, POST ]

app_logout:
  controller: App\Controller\Security\LogoutController
  path:
    en: /logout
    pl: /wyloguj
  methods: [ GET ]

oauth_facebook_connect:
  controller: App\Controller\Security\FacebookController::connect
  path: /oauth/facebook/connect
  methods: [ GET ]

oauth_facebook_verify:
  controller: App\Controller\Security\FacebookController::verify
  path: /oauth/facebook/verify
  methods: [ GET ]

oauth_google_connect:
  controller: App\Controller\Security\GoogleController::connect
  path: /oauth/google/connect
  methods: [ GET ]

oauth_google_verify:
  controller: App\Controller\Security\GoogleController::verify
  path: /oauth/google/verify
  methods: [ GET ]

oauth_github_connect:
  controller: App\Controller\Security\GithubController::connect
  path: /oauth/github/connect
  methods: [ GET ]

oauth_github_verify:
  controller: App\Controller\Security\GithubController::verify
  path: /oauth/github/verify
  methods: [ GET ]
