# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

tag_overview:
  controller: App\Controller\Tag\TagOverviewController
  path: /tag/{name}/{sortBy}/{time}/{type}
  defaults: { sortBy: newest, time: '∞', type: ~ }
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

tag_entries:
  controller: App\Controller\Tag\TagEntryFrontController
  path: tag/{name}/threads/{sortBy}/{time}/{type}
  defaults: { sortBy: newest, time: '∞', type: ~ }
  methods: [ GET ]
  requirements: { sortBy: "%front_sort_options%" }

tag_comments:
  controller: App\Controller\Tag\TagCommentFrontController
  path: tag/{name}/comments/{sortBy}/{time}/{type}
  defaults: { sortBy: newest, time: '∞', type: ~ }
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

tag_posts:
  controller: App\Controller\Tag\TagPostFrontController
  path: tag/{name}/posts/{sortBy}/{time}/{type}
  defaults: { sortBy: newest, time: '∞', type: ~ }
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

tag_people:
  controller: App\Controller\Tag\TagPeopleFrontController
  defaults: { sortBy: hot, time: ~ }
  path: tag/{name}/people
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }
