user:
  controller: App\Controller\User\UserController::front
  path: /u/{username}
  methods: [ GET ]

user_entries:
  controller: App\Controller\User\UserController::entries
  path:
    en: /u/{username}/threads
    pl: /u/{username}/treści
  methods: [ GET ]

user_entry_comments:
  controller: App\Controller\User\UserController::comments
  path:
    en: /u/{username}/comments
    pl: /u/{username}/komentarze
  methods: [ GET ]

user_posts:
  controller: App\Controller\User\UserController::posts
  path:
    en: /u/{username}/wpisy
    pl: /u/{username}/posts
  methods: [ GET ]

user_replies:
  controller: App\Controller\User\UserController::replies
  path:
    en: /u/{username}/odpowiedzi
    pl: /u/{username}/replies
  methods: [ GET ]

user_subscriptions:
  controller: App\Controller\User\UserController::subscriptions
  path:
    en: /u/{username}/subscriptions
    pl: /u/{username}/subskrypcje
  methods: [ GET ]

user_followers:
  controller: App\Controller\User\UserFollowController::followers
  path:
    en: /u/{username}/followers
    pl: /u/{username}/obserwujący
  methods: [ GET ]

user_follows:
  controller: App\Controller\User\UserFollowController::follows
  path:
    en: /u/{username}/follows
    pl: /u/{username}/obserwowani
  methods: [ GET ]

user_follow:
  controller: App\Controller\User\UserFollowController::follow
  path: /u/{username}/follow
  methods: [ POST ]

user_unfollow:
  controller: App\Controller\User\UserFollowController::unfollow
  path: /u/{username}/unfollow
  methods: [ POST ]

user_block:
  controller: App\Controller\User\UserBlockController::block
  path: /u/{username}/block
  methods: [ POST ]

user_unblock:
  controller: App\Controller\User\UserBlockController::unblock
  path: /u/{username}/unblock
  methods: [ POST ]

user_purge:
  controller: App\Controller\User\UserController::purge
  path: /u/{username}/purge
  methods: [ POST ]

user_delete:
  controller: App\Controller\User\UserController::delete
  path: /u/{username}/delete
  methods: [ POST ]

user_profile_front:
  controller: App\Controller\User\ProfileController::front
  path:
    en: /profile
    pl: /profil
  methods: [ GET ]

user_profile_notifications:
  controller: App\Controller\User\ProfileController::notifications
  path:
    en: /profile/notifications
    pl: /profil/notyfikacje
  methods: [ GET ]

user_profile_notifications_read:
  controller: App\Controller\User\ProfileController::readNotifications
  path: /profile/notifications/read
  methods: [ POST ]

user_profile_notifications_clear:
  controller: App\Controller\User\ProfileController::clearNotifications
  path: /profile/notifications/clear
  methods: [ POST ]

user_profile_magazine_blocks:
  controller: App\Controller\User\ProfileController::blockedMagazines
  path:
    en: /profile/blocklist/magazines
    pl: /profil/blokady/magazyny
  methods: [ GET ]

user_profile_user_blocks:
  controller: App\Controller\User\ProfileController::blockedUsers
  path:
    en: /profile/blocklist/people
    pl: /profil/blokady/ludzie
  methods: [ GET ]

user_profile_magazine_subscriptions:
  controller: App\Controller\User\ProfileController::subMagazines
  path:
    en: /profile/subscriptions/magazines
    pl: /profil/subskrypcje/magazyny
  methods: [ GET ]

user_profile_user_subscriptions:
  controller: App\Controller\User\ProfileController::subUsers
  path:
    en: /profile/subscriptions/people
    pl: /profil/subskrypcje/ludzie
  methods: [ GET ]

user_profile_settings:
  controller: App\Controller\User\ProfileController::settings
  path:
    en: /profile/settings
    pl: /profil/ustawienia
  methods: [ GET, POST ]

user_profile_edit:
  controller: App\Controller\User\UserController::edit
  path:
    en: /profile/edit
    pl: /profil/edytuj
  methods: [ GET, POST ]

user_profile_toggle_theme:
  controller: App\Controller\User\UserController::theme
  path:
    en: /profile/edit/theme
    pl: /profil/edytuj/wyglad
  methods: [ GET, POST ]
