user:
  controller: App\Controller\User\UserController::front
  path: /u/{username}
  methods: [ GET ]

user_entries:
  controller: App\Controller\User\UserController::entries
  path: /u/{username}/tresci
  methods: [ GET ]

user_entry_comments:
  controller: App\Controller\User\UserController::comments
  path: /u/{username}/komentarze
  methods: [ GET ]

user_posts:
  controller: App\Controller\User\UserController::posts
  path: /u/{username}/wpisy
  methods: [ GET ]

user_replies:
  controller: App\Controller\User\UserController::replies
  path: /u/{username}/odpowiedzi
  methods: [ GET ]

user_subscriptions:
  controller: App\Controller\User\UserController::subscriptions
  path: /u/{username}/subskrypcje
  methods: [ GET ]

user_followers:
  controller: App\Controller\User\UserFollowController::followers
  path: /u/{username}/obserwujacy
  methods: [ GET ]

user_follows:
  controller: App\Controller\User\UserFollowController::follows
  path: /u/{username}/obserwowani
  methods: [ GET ]

user_follow:
  controller: App\Controller\User\UserFollowController::follow
  path: /u/{username}/follow
  methods: [ POST ]

user_unfollow:
  controller: App\Controller\User\UserFollowController::unfollow
  path: /u/{username}/unfollow
  methods: [ POST ]

user_block:
  controller: App\Controller\User\UserBlockController::block
  path: /u/{username}/block
  methods: [ POST ]

user_unblock:
  controller: App\Controller\User\UserBlockController::unblock
  path: /u/{username}/unblock
  methods: [ POST ]

user_purge:
  controller: App\Controller\User\UserController::purge
  path: /u/{username}/purge
  methods: [ POST ]

user_profile_front:
  controller: App\Controller\ProfileController::front
  path: /profil
  methods: [ GET ]

user_profile_notifications:
  controller: App\Controller\ProfileController::notifications
  path: /profil/notyfikacje
  methods: [ GET ]

user_profile_notifications_read:
  controller: App\Controller\ProfileController::readNotifications
  path: /profil/notyfikacje/read
  methods: [ POST ]

user_profile_notifications_clear:
  controller: App\Controller\ProfileController::clearNotifications
  path: /profil/notyfikacje/clear
  methods: [ POST ]

user_profile_magazine_blocks:
  controller: App\Controller\ProfileController::blockedMagazines
  path: /profil/blokady/magazyny
  methods: [ GET ]

user_profile_user_blocks:
  controller: App\Controller\ProfileController::blockedUsers
  path: /profil/blokady/ludzie
  methods: [ GET ]

user_profile_magazine_subscriptions:
  controller: App\Controller\ProfileController::subMagazines
  path: /profil/Subskrypcje/magazyny
  methods: [ GET ]

user_profile_user_subscriptions:
  controller: App\Controller\ProfileController::subUsers
  path: /profil/Subskrypcje/ludzie
  methods: [ GET ]

user_profile_settings:
  controller: App\Controller\ProfileController::settings
  path: /profil/ustawienia
  methods: [ GET, POST ]

user_profile_edit:
  controller: App\Controller\User\UserController::edit
  path: /profil/edytuj
  methods: [ GET, POST ]

user_profile_toggle_theme:
  controller: App\Controller\User\UserController::theme
  path: /profil/edytuj/theme
  methods: [ GET, POST ]
