resources:
  App\DTO\BadgeDto:
    properties:
      id:
        identifier: true
    shortName: 'badge'
    collectionOperations:
      get:
        method: GET
    itemOperations:
      get:
        method: GET
    attributes:
      normalization_context:
        groups: [ 'badge_read' ]
      denormalization_context:
        groups: [ 'badge_read' ]
