resources:
  App\DTO\EntryDto:
    properties:
      id:
        identifier: true
#      comments:
#        subresource:
#          resourceClass: 'App\DTO\EntryCommentDto'
#          collection: false
    shortName: 'entry'
    collectionOperations:
      get:
        method: GET
    itemOperations:
      get:
        method: GET
      comments:
        method: GET
        path: /entries/{id}/comments.{_format}
        controller: App\Controller\Api\EntryComments
        normalization_context:
          groups: [ 'entryComment_read' ]
    attributes:
      normalization_context:
        groups: [ 'entry_read' ]
      denormalization_context:
        groups: [ 'entry_write' ]
