resources:
  App\DTO\EntryCommentDto:
    properties:
      id:
        identifier: true
    shortName: 'entry_comment'
    collectionOperations:
      get:
        method: GET
      post:
        method: POST
    itemOperations:
      get:
        method: GET
    attributes:
      normalization_context:
        groups: [ 'entryComment_read' ]
      denormalization_context:
        groups: [ 'entryComment_write' ]
