resources:
  App\DTO\MagazineDto:
    properties:
      name:
        identifier: true
    shortName: 'magazine'
    collectionOperations:
      get:
        method: GET
      post:
        method: POST
    itemOperations:
      get:
        method: GET
      badges:
        method: GET
        path: /magazines/{name}/badges.{_format}
        controller: App\Controller\Api\MagazineBadges
        normalization_context:
          groups: [ 'badge_read' ]
    attributes:
      normalization_context:
        groups: [ 'magazine_read' ]
      denormalization_context:
        groups: [ 'magazine_write' ]
