resources:
  App\DTO\PostCommentDto:
    properties:
      id:
        identifier: true
    shortName: 'post_comment'
    collectionOperations:
      get:
        method: GET
      post:
        method: POST
    itemOperations:
      get:
        method: GET
    attributes:
      normalization_context:
        groups: [ 'postComment_read' ]
      denormalization_context:
        groups: [ 'postComment_write' ]
