resources:
  App\DTO\PostDto:
    properties:
      id:
        identifier: true
    shortName: 'post'
    collectionOperations:
      get:
        method: GET
    itemOperations:
      get:
        method: GET
      comments:
        method: GET
        path: /posts/{id}/comments.{_format}
        controller: App\Controller\Api\PostComments
        normalization_context:
          groups: [ 'postComment_read' ]
    attributes:
      normalization_context:
        groups: [ 'post_read' ]
      denormalization_context:
        groups: [ 'post_write' ]
