resources:
  App\DTO\UserDto:
    properties:
      username:
        identifier: true
    shortName: 'user'
    collectionOperations:
      get:
        method: GET
      post:
        method: POST
    itemOperations:
      get:
        method: GET
    attributes:
      normalization_context:
        groups: [ 'user:read' ]
      denormalization_context:
        groups: [ 'user:write' ]
